name: Markdown Link Check

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.md'
      - '.github/workflows/check-markdown-links.yaml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/*.md'
      - '.github/workflows/check-markdown-links.yaml'
  workflow_dispatch:

jobs:
  linkcheckmd:
    name: 'Check Markdown Links'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install linkcheckmd
        run: |
          python -m pip install --upgrade pip
          pip install 'linkcheckmd==1.4.0'

      - name: Check Markdown links
        run: python -m linkcheckmd .
